# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buoyant-apogee-295608
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reducer
  template:
    metadata:
      labels:
        app: reducer
    spec:
      containers:
      - name: reducer
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/buoyant-apogee-295608/roy2@sha256:884b4bee80a7030aa68cbf79af03c702573354266e5786aeba0edc32fa9cfa1f
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: "3000"
